spring:
  data:
    mongodb:
      host: ${OPENSHIFT_MONGO_DB_HOST}
      port: ${OPENSHIFT_MONGO_DB_PORT}
      username: ${OPENSHIFT_MONGO_DB_USERNAME}
      password: ${OPENSHIFT_MONGO_DB_PASSWORD}
      database: ${OPENSHIFT_MONGO_DB_DATABASE}
      uri: ${OPENSHIFT_MONGO_DB_URL}